# Generated by Django 4.2.16 on 2024-11-22 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=255)),
                ('idioma', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(max_length=1000)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo')], max_length=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idioma', models.CharField(max_length=255)),
                ('n_cartoes', models.IntegerField()),
                ('n_dominados', models.IntegerField()),
                ('n_aprender', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado_frente', models.CharField(max_length=255)),
                ('lado_tras', models.CharField(max_length=255)),
                ('dica_1', models.CharField(blank=True, max_length=255, null=True)),
                ('dica_2', models.CharField(blank=True, max_length=255, null=True)),
                ('dica_3', models.CharField(blank=True, max_length=255, null=True)),
                ('n_revisoes', models.IntegerField()),
                ('maduro', models.BooleanField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_revisao', models.DateTimeField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_arquivo', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.usuario')),
            ],
        ),
    ]
