# Generated by Django 4.2.16 on 2024-11-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='id_arquivo',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='deck',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
