# Generated by Django 4.2.16 on 2024-11-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_arquivo_classe_remove_arquivo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='conteudo',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(default='PDF', max_length=50),
        ),
    ]
