# Generated by Django 4.2.16 on 2024-11-22 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0005_classe_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
