# Generated by Django 4.2.16 on 2024-11-23 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_notificacao_classe_alter_notificacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='resposta_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='classes.mensagem'),
        ),
    ]
