# Generated by Django 5.1.1 on 2024-11-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_alter_deck_n_aprender_alter_deck_n_dominados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='n_aprender',
        ),
    ]
