# Generated by Django 4.2.16 on 2024-11-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_alter_card_data_ultima_revisao_alter_card_maduro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='tipo',
        ),
    ]
