# Generated by Django 5.1.1 on 2024-11-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_remove_mensagem_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='n_cartoes',
        ),
    ]
