# Generated by Django 5.1.1 on 2024-11-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_remove_deck_n_cartoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='n_dominados',
        ),
    ]
