# Generated by Django 4.2.16 on 2024-11-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$dhECv3jEFj4Lq7cCTrRguF$VKPHPyFkdKv9XQ68++84RIA/S4ui10a+AUA45GEYXus=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
    ]
