# Generated by Django 4.2.16 on 2024-11-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usuario_password_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$dwW4ZFlEIl5X3qRyNMkuSk$0/NnxxE/UU+6qbxsmX+IXJu7ADRtbA6SGOcu2b1iwLQ=', max_length=128),
        ),
    ]
