# Generated by Django 4.2.16 on 2024-11-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$93AyMehiNV8Nyof2Vk6IIV$p6t7g2NRn1k8HQhavQWAkhce44WtsZSFlNwjMG2BjnM=', max_length=128),
        ),
    ]
