# Generated by Django 4.2.16 on 2024-11-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$KvUcBlA0zetyClw4JZvEks$gCjpG+n8NHTWjFx0hnYGM1ukxGr6NrJtfPDq9vjg7Vo=', max_length=128),
        ),
    ]
