# Generated by Django 4.2.16 on 2024-11-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$StlNGoXABtpVa5aLnTaVnz$SxApWio951SsitH5dAaF5rf2pOqBxLCnLsqQLEuhKlI=', max_length=128),
        ),
    ]
