# Generated by Django 4.2.16 on 2024-11-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LhEdL2hjjicMhUxiLwi3iJ$m07o5CZKtkudvNIfTMOXskCSovabwrrwoqIg3VeTGQ8=', max_length=128),
        ),
    ]
