# Generated by Django 4.2.16 on 2024-11-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$vvWppJXlp7oWMYrBVKKRz5$BCTMDfp/6WEzzDW8w8c+Cj3onYNVNt3LI2l26NkGgYA=', max_length=128),
        ),
    ]
