# Generated by Django 4.2.16 on 2024-11-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usuario_poster_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Ioo43iAwQvLsmSk0ghFDr9$/SoPQALCaboaTBCwSlEK1D9obWsYc9ZlrYEKtrSd6so=', max_length=128),
        ),
    ]
