# Generated by Django 4.2.16 on 2024-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Ce2OxRMEWqzhf76YBmPJtd$OgqK3IqcF/3QvvIct/X5uI1e45G5Sp2+SivEFQ4XYyA=', max_length=128),
        ),
    ]
