# Generated by Django 4.2.16 on 2024-11-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$n5uKTBuxQg4IXx2J5bXza8$mCmcd3jqqdZBHRHPaM79mN6x0gTybQO6jNhuXTDOTdw=', max_length=128),
        ),
    ]
