# Generated by Django 4.2.16 on 2024-11-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$IB6LjZvaK5xzN63mO8EPop$0zm9zTABnZSPLHHsChAt2j3O3o1tbGfthu63x8vjK84=', max_length=128),
        ),
    ]
