# Generated by Django 4.2.16 on 2024-11-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jvjfwl885neS9odLzDk5GU$8oSq/qPtxZR1W+GdEq1b0chTbeclVpsYl8/QxvvzGCY=', max_length=128),
        ),
    ]
