# Generated by Django 4.2.16 on 2024-11-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$UEPxVmlgM0D63zPgZGhlF2$zLrEL5WA6D352glr0rZYlWqx3uMJ7AShSk9Vtw6BZ5w=', max_length=128),
        ),
    ]
