# Generated by Django 5.1.1 on 2024-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$7XcrckvHlwIpSwAqCNlkqx$1H9Qx+6Pvnnj96W0vu4TDpbSh+/Sy+8+H4TSKZUgrMQ=', max_length=128),
        ),
    ]
