# Generated by Django 5.1.1 on 2024-11-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Mrc89ig3JMw66vbTlFGgq5$bRlFtjAbHU74Zb6oVqCXhVhxT+tSFx6GfYhyXuzEFnM=', max_length=128),
        ),
    ]
