# Generated by Django 5.1.1 on 2024-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$udyZeiWQcg0XvmvLB3nCvp$CmIzk6wvm0eJt2j2zn832Ql23a66rf+kc8U06M2uJeo=', max_length=128),
        ),
    ]
