# Generated by Django 5.1.1 on 2024-11-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$yqlTaO0aQWF23jt9pTtjOC$pZWNn62/BwqfXDDkF3asPKizs6NAeiHGsELmD2JgqWo=', max_length=128),
        ),
    ]
