# Generated by Django 4.2.16 on 2024-11-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$73VqsPvmc8Fg1x8zI1Y1yt$GRm+30uGrgEhLmOdbUAq7bWVhzieTw/BAbkws30sONU=', max_length=128),
        ),
    ]
