# Generated by Django 4.2.16 on 2024-11-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$SUkrkP9DV7NsGXDHpgDPpR$xg8X0JD+O367u40Gx5F1usuhaYGZpua416+4ixGANoc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
