# Generated by Django 5.1.1 on 2024-11-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$a0cU4IeiEaC8mlRmmQ6uXt$pzPVK44WPxYGLZSojbZ6bqOdP96NlkhmtZQlsmRxjio=', max_length=128),
        ),
    ]
