# Generated by Django 5.1.1 on 2024-11-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$B6oJwhii6Ib6mTYWvo1ksp$dty5San4UBmpOx/9poIZlz2Gycohfwgo0lx41glMhF4=', max_length=128),
        ),
    ]
