# Generated by Django 5.1.1 on 2024-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$wDBcvizdJhGOuEt9PeMDga$W2/Y200dBmAAEyTpk5Ak+Tn5AOA9/k4qYa7PGYJZrkc=', max_length=128),
        ),
    ]
